### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by AMDmi3** [lambdalisue/rs-metrics-process#57]
Could you please tag a new release with recently merged FreeBSD support changes?

**Comment by lambdalisue** [comment]
Hum...? I've released v2.2.0 already
https://crates.io/crates/metrics-process

**Comment by lambdalisue** [comment]
Ah, only crates.io was updated. Now, GitHub is updated.

**Comment by AMDmi3** [comment]
Thank you! I've looked at https://github.com/lambdalisue/rs-metrics-process/tags, I guess the tag is still missing.

**Comment by lambdalisue** [comment]
Oops. Pushed.
